---
site_name: hexagonal-and-clean-architecture-training
site_url: https://github.com/MatthiasEschhold/hexagonal-and-clean-architecture-training
repo_url: https://github.com/MatthiasEschhold/hexagonal-and-clean-architecture-training.git
repo_name: MatthiasEschhold/hexagonal-and-clean-architecture-training
edit_uri: edit/develop/documentation/docs/

extra_css:
  - css/custom.css

markdown_extensions:
  - abbr
  - admonition
  - footnotes
  - attr_list
  - toc:
      toc_depth: 2-6
      permalink: ⚓︎
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

theme:
  name: material
  docs_dir: docs
  custom_dir: docs/overrides
  logo: docs/img/logo.png
  favicon: docs/img/logo.png
  icon:
    repo: fontawesome/brands/github
    edit: material/file-edit-outline
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.footer
    - content.code.copy
    - content.action.edit
    - content.action.view

plugins:
  - search

nav:
  - Home: 'index.md'
  - Aufgabenbeschreibung: 'mkdocs.md'
  - Domänenmodell: 'docs/lab1/lab1.md'
  - Use Cases: 'docs/lab2/lab2.md'
  - Adapters: 'docs/lab3/lab3.md'
  - Wachstum des Domain Module: 'docs/lab4/lab4.md'
  - Wachstum des Systems: 'docs/lab5/lab5.md'
  - Git Utils: 'docs/help/git.md'
